import { Task } from '../types';

export const mockTasks: Task[] = [
  {
    id: '1',
    title: '完成项目需求文档',
    description: '整理并编写完整的项目需求分析文档',
    assignee: '张三',
    dueDate: '2026-04-05',
    priority: 'high',
    status: 'todo',
    createdAt: '2026-03-28',
  },
  {
    id: '2',
    title: '设计数据库架构',
    description: '设计并优化系统的数据库表结构',
    assignee: '李四',
    dueDate: '2026-04-08',
    priority: 'high',
    status: 'inprogress',
    createdAt: '2026-03-29',
  },
  {
    id: '3',
    title: '前端组件开发',
    description: '开发首页的主要 UI 组件',
    assignee: '王五',
    dueDate: '2026-04-10',
    priority: 'medium',
    status: 'inprogress',
    createdAt: '2026-03-30',
  },
  {
    id: '4',
    title: 'API 接口文档',
    description: '编写后端 API 接口说明文档',
    assignee: '赵六',
    dueDate: '2026-04-03',
    priority: 'low',
    status: 'done',
    createdAt: '2026-03-25',
  },
  {
    id: '5',
    title: '用户测试计划',
    description: '制定用户测试的详细计划和用例',
    assignee: '张三',
    dueDate: '2026-04-15',
    priority: 'medium',
    status: 'todo',
    createdAt: '2026-03-31',
  },
  {
    id: '6',
    title: '性能优化方案',
    description: '分析系统性能瓶颈并提出优化方案',
    assignee: '李四',
    dueDate: '2026-04-12',
    priority: 'high',
    status: 'todo',
    createdAt: '2026-04-01',
  },
  {
    id: '7',
    title: '代码规范制定',
    description: '制定团队统一的代码规范和最佳实践',
    assignee: '王五',
    dueDate: '2026-04-06',
    priority: 'low',
    status: 'inprogress',
    createdAt: '2026-03-27',
  },
  {
    id: '8',
    title: '项目部署脚本',
    description: '编写自动化部署脚本和配置',
    assignee: '赵六',
    dueDate: '2026-04-09',
    priority: 'medium',
    status: 'done',
    createdAt: '2026-03-20',
  },
  {
    id: '9',
    title: '安全扫描配置',
    description: '配置代码安全扫描工具',
    assignee: '张三',
    dueDate: '2026-04-07',
    priority: 'medium',
    status: 'todo',
    createdAt: '2026-03-26',
  },
  {
    id: '10',
    title: 'UI 设计稿评审',
    description: '评审并确认最终的 UI 设计稿',
    assignee: '李四',
    dueDate: '2026-04-04',
    priority: 'high',
    status: 'done',
    createdAt: '2026-03-22',
  },
];
